name = "floogic-mcp-server"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
GOOGLE_CALENDAR_CLIENT_EMAIL = "floogic-calendar-agent@flowise-calendar-agent.iam.gserviceaccount.com"
# Note: The private key should be set using `wrangler secret put GOOGLE_CALENDAR_PRIVATE_KEY` 